version: '2'

services:
    
    rabbitmq:
        image: rabbitmq:3.6.5-management
        ports:
            - '15672:15672'
        env_file: rabbitmq.env
            
    
    test-sensor:
        image: defyndian/test-sensor
        depends_on:
            - rabbitmq
    
    test-actor:
        image: defyndian/test-actor
        depends_on:
            - rabbitmq
